# Docker Compose file for InfCloud and a Baikal server
# Based on issue https://github.com/ckulka/baikal-docker/issues/13

# The changes to the config-baikal.js file are adjustments in globalNetworkCheckSettings.href (line 335)
#
# For this setup to work, you also have to change WebDAV authentication type to Basic:
#
# 1. Go to Baikal Settings (http://baikal.localhost/admin/?/settings/standard/)
# 2. Change "WebDAV authentication type" to "Basic"

version: "2"

services:
  infcloud:
    image: ckulka/infcloud
    restart: always
    depends_on:
      - php
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: infcloud.localhost"
      traefik.port: 80
    volumes:
      - infcloud:/usr/share/nginx/infcloud
      - ./config-baikal.js:/usr/share/nginx/infcloud/config.js:ro

  php:
    image: php:7.3-fpm-alpine
    restart: always
    volumes:
      - infcloud:/usr/share/nginx/infcloud:ro

  baikal:
    image: ckulka/baikal:experimental-nginx
    restart: always
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: baikal.localhost"
      traefik.port: 80
    volumes:
      - ./baikal-nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # See https://docs.traefik.io/
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --accesslog
      - --docker
      - --docker.exposedByDefault=false

volumes:
  infcloud:
