version: "2"

services:
  infcloud:
    image: ckulka/infcloud
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js:ro

  php:
    image: php:7.3-fpm-alpine
    restart: always
    volumes_from:
      - infcloud:ro
