#!/bin/bash

# Custom build script to build images for all supported architectures.
# Example for IMAGE_NAME: ckulka/infcloud:latest

for arch in amd64 arm64v8
do
  echo "Building $IMAGE_NAME-$arch"
  docker build --build-arg FROM_ARCH=$arch --file $DOCKERFILE_PATH --tag $IMAGE_NAME-$arch .
done

# arm32v7/nginx unfortunately has different tags and Alpine doesn't exist
echo "Building $IMAGE_NAME-arm32v7"
docker build --build-arg FROM_ARCH=arm32v7 --build-arg FROM_VARIANT=1 --file $DOCKERFILE_PATH --tag $IMAGE_NAME-arm32v7 .
